name: stoneassemblies-massauth
network: stoneassemblies-massauth-network
services:
- name: stoneassemblies-massauth-server
  image: stoneassemblies/massauth-server:1.0.0-alpha0144
  replicas: 1
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: RabbitMQ:Address
    value: rabbitmq://host.docker.internal:6002
  - name: RabbitMQ:Username
    value: queuedemo
  - name: RabbitMQ:Password
    value: queuedemo
  - name: Extensions:Sources:0:Uri
    value: /app/local-packages
  - name: Extensions:Sources:1:Uri
    value: http://host.docker.internal:8081/repository/nuget.org-proxy/index.json
  - name: Extensions:Packages:0
    value: StoneAssemblies.MassAuth.Benchmarks.Rules:1.0.0-alpha0021
  volumes:
  - source: ../../output/nuget-symbols
    target: /app/local-packages
- name: rabbitmq
  image: rabbitmq:3.11.17-management
  bindings:
  - name: rabbitmq
    port: 6002
    containerPort: 5672
    protocol: tcp
  - name: https
    port: 6003
    containerPort: 15672
    protocol: http
  env:
  - name: RABBITMQ_DEFAULT_USER
    value: queuedemo
  - name: RABBITMQ_DEFAULT_PASS
    value: queuedemo