name: stoneassemblies-massauth
network: stoneassemblies-massauth-network
services:
- name: stoneassemblies-massauth-server
  image: stoneassemblies/massauth-server:1.0.0-alpha0057
  replicas: 5
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: RabbitMQ:Address
    value: rabbitmq://172.24.0.1:6002
  - name: RabbitMQ:Username
    value: queuedemo
  - name: RabbitMQ:Password
    value: queuedemo
  - name: Extensions:Sources:0
    value: http://172.24.0.1:8081/repository/nuget-all/
  #  value: https://api.nuget.org/v3/index.json
  #  value: ../../output/nuget-symbols/
  - name: Extensions:Packages:0
    value: StoneAssemblies.MassAuth.Benchmarks.Rules
- name: rabbitmq
  image: rabbitmq:3.8.3-management
  bindings:
  - name: rabbitmq
    port: 6002
    containerPort: 5672
    protocol: tcp
  - name: https
    port: 6003
    containerPort: 15672
    protocol: http
  env:
  - name: RABBITMQ_DEFAULT_USER
    value: queuedemo
  - name: RABBITMQ_DEFAULT_PASS
    value: queuedemo
- name: stoneassemblies-massauth-proxy
  image: stoneassemblies/massauth-proxy:1.0.0-alpha0057
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: RabbitMQ:Address
    value: rabbitmq://172.24.0.1:6002
  - name: RabbitMQ:Username
    value: queuedemo
  - name: RabbitMQ:Password
    value: queuedemo
  - name: Extensions:Sources:0
    value: http://172.24.0.1:8081/repository/nuget-all/
  #  value: https://api.nuget.org/v3/index.json
  #  value: ../../output/nuget-symbols/
  - name: Extensions:Packages:0
    value: StoneAssemblies.MassAuth.Benchmarks.Messages
  bindings:
  - name: ingress
    port: 6004
    containerPort: 80
    protocol: http